---
dependency:
  name: galaxy
driver:
  name: docker
#lint: |
#  ansible-lint
platforms:
  - name: ubuntu
    image: geerlingguy/docker-ubuntu2004-ansible
    dockerfile: Dockerfile.js
provisioner:
  name: ansible
  inventory:
    host_vars:
      ubuntu:
        ansible_user: nick    
verifier:
  name: ansible
